### ISSUE TITLE
Runic Shears improvements

### ISSUE THREAD

**Issue by noobanidus** [MysticMods/Roots#102]
Currently the runic shears are only used to obtain:

1. Wheat -> wildewheet
2. Beetroot -> spirit herb (only sources)
3. Carrot -> aubergine

With their functionality of transmuting animal shearings into drops removed, I'd like to suggest some of the following:

1. Directly extracting iron and gold ingots from ores
2. "Fortune"-like effect when used on grass, leaves, flowers, (vanilla only) which gives a chance for additional drops.
3. Likewise fortune-like effect when used to shear sheep, giving a chance of additional drops.

It's possible we could also add a "lanolin"-like substance which could be obtained with the runic shears that could have uses in the preparation of certain types of incense or spells.

What this thread aims to do:

Throw about ideas for unique interactions with vanilla and modded mechanics (specifically modded to the Mystical family) that make them more useful than just "once you get your initial stock of wildewheet and spirit herb, don't bother using them".

I'm happy for them to be superseded by Animal Harvest however for animal drops specifically, but for additional animal drops I'm happy to add them. For example, horned deer variants could drop "velvet".

How this ties in to groves is something else that will need iteration.

**Comment by Febilian** [comment]
Adding to this, I'd suggest maybe adding incentive to use the runic shears to get terra moss from mossy stone over knives... like maybe a higher yield per block 'sheared' this way.

The idea of being able to use the shears for secondary creature bits suggested here seems appealing too, like maybe getting tufts of fur from foxes, slime from the frogs, etc. I'd have to think a little more to suggest what you'd get from beetles and deer...

But yeah, I agree that right now you basically make the runic shears, get the 2 herbs that require it, and then never use them again - and that makes them seem kind of superfluous. Would 100% support them being more useful in some way.

**Comment by duely** [comment]
^ This is my primary purpose for this thread. If anyone else has any ideas for other uses for runic shears, that would be great. Extracting *something* out of nothing would make sense.

Additional chances for terra moss wouldn't necessarily negate knives as they're still required for bark.

I think tallgrass, ferns and dead bushes have additional chances would also be good; likewise flowers, although they aren't necessarily used for anything at the minute.

Therefore, additions would be:

- Extracting things from plants (besides those listed above)
- Extracting things from animals (^)
- Extracting things from blocks (besides terra moss)
- Extracting things from liquids

Even having them additionally act as a normal pair of self-repairing (living) shears would be an improvement.

- Extracting things from mobs: rotten flesh (low chance) from zombies, bones from skeletons -- a sort of ... "pick pocketing" as it were?

**Comment by duely** [comment]
This was implemented in part but some of the ideas are still workable.

**Comment by noobanidus** [comment]
Honestly, at this point I'm happy with the options available.
