### ISSUE TITLE
Implement compatibility for Rustic crops with Harvest spell

### ISSUE THREAD

**Issue by gchpaco** [MysticMods/Roots#125]
If you have Rustic herbs growing, and cast the harvest spell, the full grown ones will be returned to growth stage 1 as normal, but no herbs will actually be harvested.

**Comment by duely** [comment]
This is actually really weird and I'm curious to see why but then I'm also scared to go back into that code because I just copy/pasted it for some reason and I don't remember why. So there's a duplicate somewhere...

**Comment by gchpaco** [comment]
Possibly relevant, when casting it on tomato / chili vines the vine blocks themselves reduce to growth stage 1 instead of just popping the fruit, and with grape vines the stem of the grape vine is reduced to growth stage 1.

**Comment by duely** [comment]
Okay, this is a wider issue than I expected it would be. I don't think it will make the 3.0.2 release but I am working on excluding Rustic crops by default so you don't lose anything.

**Comment by noobanidus** [comment]
I think the current blacklist system handles this pretty well; I don't want to have to special-case all of the crops.
