### ISSUE TITLE
Sylvan/Wildwood chestplate doesn't glow on the chest when enchanted

### ISSUE THREAD

**Issue by VallenFrostweaver** [MysticMods/Roots#137]
Minecraft 1.12.2
Forge: 14.23.5.2836
Roots: 3.0.0 (3.0.2)

![no enchant](https://user-images.githubusercontent.com/13642054/60723809-9ba26780-9f2c-11e9-976b-cdc9967266f9.png)
![im sure](https://user-images.githubusercontent.com/13642054/60724762-2c7a4280-9f2f-11e9-8f80-a6546e0a5110.png)
![double check](https://user-images.githubusercontent.com/13642054/60724763-2d12d900-9f2f-11e9-824f-7f1c825738c9.png)

EDIT: It should be noted that Quark runes do not alter the enchant color as they should too. It does on the item but not when displayed on the player.

**Comment by duely** [comment]
That ... is really weird. And with your skin I just... wow.

**Comment by duely** [comment]
Worth noting is that this is specifically the `chest` pieces that make up the various parts of the armor rather than any of the other parts that are rendered separately (head, arms, etc)

**Comment by VallenFrostweaver** [comment]
FYI - the center of the chestplate doesn't even show up now... v 3.0.5

**Comment by SkyLord-Volmir** [comment]
I'm on 3.0.0 and the chest portion of the wildwood chestplate doesn't show up on my character.  When I first put it on, I thought it looked like it flew up off me into the sky.  When looking above me, I saw a small dot.  After doffing then donning it again, it no longer showed up above me in the sky in third person view.  I believe it's a cumulative shift in the coordinate of the armor or something.

**Comment by duely** [comment]
@SkyLord-Volmir That was fixed in 3.0.5 I believe.

**Comment by duely** [comment]
Is this still occurring @VallenFrostweaver ?

**Comment by VallenFrostweaver** [comment]
Nope. Fixed.
