### ISSUE TITLE
Wildwood armor regen allows infinite waterbreathing

### ISSUE THREAD

**Issue by VallenFrostweaver** [MysticMods/Roots#144]
Minecraft 1.12.2
Forge: 14.23.5.2836
Roots: 3.0.0 (3.0.2)
While I love the fact Wildwood armor regens you instead of itself it is strong enough of a health regen to offset the damage from running out of breath bubbles when underwater. This may be as intended and make it that much more useful/powerful armor but I thought I'd mention it here just in case.

**Comment by duely** [comment]
That's an interesting point. I'm not actually sure what the damage rate is, but the heal shouldn't be that fast. I think it's possibly just a slight imbalance issue. Alternately, it could be configured not to heal when the player is out of breath.

**Comment by VallenFrostweaver** [comment]
If it doesn't heal when out of breath then what about getting attacked underwater at that time? It would make the armor then weaker in water in general. Maybe it could give a different effect instead of regen in water?

**Comment by duely** [comment]
I've adjusted how the heal works but increased the chance of the heal occurring to compensate. I think this might help offset this issue without dramatically nerfing it/changing the effect completed/special-casing drowning damage.

**Comment by duely** [comment]
There are some changes in the most recent build that might hopefully address this (3.0.3)

**Comment by duely** [comment]
I think this is truly fixed now.
