### ISSUE TITLE
Broken wildwood fence texture in inventory

### ISSUE THREAD

**Issue by VallenFrostweaver** [MysticMods/Roots#146]
Minecraft 1.12.2
Forge: 14.23.5.2836
Roots: 3.0.0 (3.0.2)
Only broken texture in inventory. Seems fine in world.
![broken fence](https://user-images.githubusercontent.com/13642054/60840414-59488700-a1c7-11e9-8d5f-91109a4c6437.png)

**Comment by duely** [comment]
Assigned to the squid.

**Comment by Davoleo** [comment]
I think you closed the wrong one @duely :P

**Comment by duely** [comment]
Oops, my bad.
