### ISSUE TITLE
Bauble slot models

### ISSUE THREAD

**Issue by jaesunn** [MysticMods/Roots#150]
So I notice you add pouches with unique slots for Phials and Herbs. I think it would be cool if you could add a model with it as well. It can consist of S strap with pouches, phials and herbs. This idea could also work with the quivers.

**Comment by noobanidus** [comment]
This isn't something that I have the artistic time nor the skill to do. I feel like it would be best pushed forward to 3.2 in 1.14/1.15 when we have more suitable art assets/time and models.
