### ISSUE TITLE
Magnetism spell has a teleport glitch at around ~15 blocks

### ISSUE THREAD

**Issue by VallenFrostweaver** [MysticMods/Roots#151]
Minecraft 1.12.2
Forge: 14.23.5.2836
Roots: 3.0.0 (3.0.2)
When using the magnetism spell it works like a charm but at around the ~15 block distance (or the farthest point) it teleports what looks like the item(s) to you and then they teleport back.

![Magnetism](https://user-images.githubusercontent.com/13642054/61366763-1c912580-a882-11e9-8577-7e17d2c04643.gif)

**Comment by duely** [comment]
This is curious and I wonder if perhaps there's an oversight that results in entities behind moved both on the client and the server side -- but the server side doesn't actually move it, and when it synchronises a short time later it "teleports" back...
