### ISSUE TITLE
Crash: Roots render Crash with TileEntityOffertoryPlateRenderer

### ISSUE THREAD

**Issue by SirAron111** [MysticMods/Roots#156]
Crash: Roots render Crash with TileEntityOffertoryPlateRenderer
I don’t know what caused it but there is a crash happening with the crash log saying something about the offertory plate renderer
[OPlate.txt](https://github.com/MysticMods/Roots/files/3438132/OPlate.txt)
https://pastebin.com/CGWQtp1L

Roots-1.12.2-3.0.4.jar
Forge 14.23.5.2838

**Comment by samakotleta** [comment]
one of my pals have same issue, appears only if there is something placed on plate, there is his crashlog
https://paste.dimdev.org/himiwamoja.mccrash

**Comment by duely** [comment]
I'm looking into it now and aim to have a new release out tomorrow that fixes (at least) this bug and the memory leak with armor.
