### ISSUE TITLE
forest pyre ritual causes some saplings/trees to only exist clientside

### ISSUE THREAD

**Issue by majijn** [MysticMods/Roots#158]
version: Roots-1.12.2-3.0.4
forge: forge-14.23.5.2838

i havent figured what causes some to be  only client side and which exist both sides however.

**Comment by duely** [comment]
Also fixed by 4be3fdf

**Comment by duely** [comment]
Oh, it's simply this: trees were being grown on both the client side and the server side. The ones on the server side only appear to exist, but don't actually.
