### ISSUE TITLE
[request] tweaking forest growth pyre ritual

### ISSUE THREAD

**Issue by majijn** [MysticMods/Roots#159]
would it be possible for the ritual to favour planting the tree type closes to the pyre?

**Comment by duely** [comment]
It should already be doing this tbh

**Comment by majijn** [comment]
;-; its the behaviour i was expecting, too, but it keeps choosing freaking oaks.

**Comment by majijn** [comment]
the problem may be different than i thought, as now im a test world, all trees seem to be giving oak saplings, ive tested  1x1 jungle , 2x2 jungle, 2x2 spruce , and dark oak trees so far
