### ISSUE TITLE
wildwood leaves are always on fancy rendering, even when fast rendering is selected.

### ISSUE THREAD

**Issue by majijn** [MysticMods/Roots#160]

**Comment by duely** [comment]
I ... don't even know what this means tbh. Can you provide a screenshot to demonstrate?

**Comment by majijn** [comment]
![2019-08-04_07 58 19](https://user-images.githubusercontent.com/18368034/62421837-914cc800-b6a8-11e9-89f4-23867f1bcaa0.png)

**Comment by duely** [comment]
I see. I'll have to look closer into the Vanilla rendering system as I was of the opinion that I'd done everything properly.
