### ISSUE TITLE
Radiance particle gravity results in a "dual" beam, seemingly from the player's feet as well as torso.

### ISSUE THREAD

**Issue by majijn** [MysticMods/Roots#162]
instead of the hand, wand, center of the character's hitbox or eyes of the character
this is more easily observed in third person.

**Comment by duely** [comment]
Upon further consideration, I believe this is specifically linked to the "spiral"/additional particle that spawns slightly beneath and has strong gravity, resulting in it falling to the ground. As it is consistently falling, it appears as though there is a double line...
