### ISSUE TITLE
Adding bark recipes via CraftTweaker does not keep item/block metadata

### ISSUE THREAD

**Issue by Charnuz** [MysticMods/Roots#164]
Adding recipes will default to metadata 0 on both the block, and the output.

``mods.roots.Bark.addRecipe("melon", <minecraft:melon_block>, <minecraft:sand>);`` works as intended.

``mods.roots.Bark.addRecipe("pumpkin_to_red_sand", <minecraft:pumpkin>, <minecraft:sand:1>);`` will still output normal sand, instead of red sand.

``mods.roots.Bark.addRecipe("mossy_brick_to_gray_dye", <minecraft:stonebrick:1>, <minecraft:dye:8>);`` will use normal stone bricks instead of mossy stone bricks, and output an ink sac instead of gray dye.

![error](https://user-images.githubusercontent.com/16440978/62622743-af9f0780-b8e4-11e9-9afd-d305bc4e033b.png)

**Comment by duely** [comment]
This is my fault for failing to specify that the metadata currently isn't being recorded, although I did specify the quantity. I ran out of time before the initial release and it slipped my mind in the interim: I actually need to refactor how everything is stored in the bark recipes to get it to work as expected.

**Comment by duely** [comment]
This should be in the next release, however it will still be looking specifically for a block rather than for a block state -- so blocks with variants will still be difficult/impossible to implement.

**Comment by Charnuz** [comment]
Thanks! Perhaps adding support for the metadata wildcard ``<minecraft:stonebrick:*>`` to use the old behavior could help with blocks that have multiple states. Of course, it won't be perfect.
