### ISSUE TITLE
Magmatic soil partial functionality

### ISSUE THREAD

**Issue by VallenFrostweaver** [MysticMods/Roots#165]
Minecraft 1.12.2
Forge: 14.23.5.2836
Roots: 3.0.5
When planting potatoes on magmatic soil and bonemealing to grow only some of the potatoes harvested are cooked.

**Comment by duely** [comment]
I think this is deliberately so that there's always seed potatoes left over.

**Comment by VallenFrostweaver** [comment]
Ah. I see. I am getting one uncooked each time. I have right click to harvest in there so it shorts the result once because of that. I understand now.

**Comment by duely** [comment]
Ah, that's interesting and unfortunately difficult to program around depending on which right-click harvest implementation you're using... I need to double check what @EpicSquid actually said but I know that it was definitely not everything getting cooked.
