### ISSUE TITLE
Aqueous Soil auto harvest fail

### ISSUE THREAD

**Issue by VallenFrostweaver** [MysticMods/Roots#166]
Minecraft 1.12.2
Forge: 14.23.5.2836
Roots: 3.0.5
Planted Dewgonia and potatoes on Aqueous soil. Grew both with bonemeal and/or Rampant Growth spell. No auto harvest happened into hoppers/chests below or on top of the soil if blocked. I manually harvested and some went below and some didn't but not in consistent numbers and most were on top and very few went below (if available).

**Comment by majijn** [comment]
#161

**Comment by VallenFrostweaver** [comment]
Ah. I did a search for Aqueous... not water...
