### ISSUE TITLE
Pereskia bulbs on Elemental Soil will sometimes auto cook

### ISSUE THREAD

**Issue by VallenFrostweaver** [MysticMods/Roots#167]
Minecraft 1.12.2
Forge: 14.23.5.2836
Roots: 3.0.5
Planted Pereskia bulbs in an area of normal tilled land and a similar area of Elemental Soil (NOT magmatic - just plain Elemental Soil) and when I harvest I get a small number of bulbs returned as cooked. I used the Harvest spell and also manually harvest and got the same results.

**Comment by duely** [comment]
That's definitely a bug. Delicious, but a bug! I'll look into it.
