### ISSUE TITLE
Rewrite Patchouli book to conditionally enable/disable pages based on disabled/enabled rituals

### ISSUE THREAD

**Issue by SirAron111** [MysticMods/Roots#168]
I disabled the ritual that changes day/night times so it won’t mess with astral sorcery and HW invasions timers. But the book now sends this as an error message is this normal?

![2019-08-09_18 17 20](https://user-images.githubusercontent.com/39855956/62793507-07e72c80-bad2-11e9-8ec1-e7f912affaa6.png)

**Comment by SirAron111** [comment]
also seems to crash when looking at spells and the like https://pastebin.com/xd3SQ7wM

**Comment by SirAron111** [comment]
I resolved the issue for me (didn’t fix the bug but made it so it doesn’t crash my modpack) I simply enabled the ritual again this resolved the error instead I literally made it unusable by making all ingredients in the scrip be creative item locks XD… but the issue I reported remains. Hope it’s fixable for you.

**Comment by duely** [comment]
Yeah, honestly I'm not super-sure about how to approach this, but given that this is an option, we definitely need to look at doing it.
