### ISSUE TITLE
Check into whether elemental soil gives hydrated crop growth boost

### ISSUE THREAD

**Issue by Purple-Towel** [MysticMods/Roots#169]
As is the title, I was asked by Nooby on Discord to mark this issue for investigation.

**Comment by EpicSquid** [comment]
It does, see here: https://github.com/MysticMods/Roots/blob/master/src/main/java/epicsquid/roots/block/BlockElementalSoil.java#L180

**Comment by Purple-Towel** [comment]
I'm not particularly well versed in what function that line is calling (by the name isFertile it could mean that it just checks if it's a valid planting surface), but I think when Nooby asked me to open this on the tracker he wanted to look into if the actual speed growth mechanics of vanilla hydrated soil were being applied correctly or if it was weird hardcoding.
