### ISSUE TITLE
Crash when opening The Druidic Arts book

### ISSUE THREAD

**Issue by angelnc1989** [MysticMods/Roots#171]
https://paste.dimdev.org/tizucijese.mccrash

I  clicked next on a page (can't remember which), the game crashed and now everytime I open the book it crashes again.

**Comment by duely** [comment]
Unfortunately this is an issue with Patchouli & Mystical Lib interacting in a strange way. I tried to work with Vazkii to fix it, but the best solution we came up with was to just avoid rendering in the first place -- this is the visualisation for the rituals.

If you're unable to actually open the book, I'd recommend deleting the patchouli_data.json file from your client and see if that fixes it.

**Comment by Jeleven99** [comment]
I have tried this solution, but this situation happends again. The patchouli_data.json file is automatically generated when I check the  client.

**Comment by noobanidus** [comment]
I'm sorry, please make an issue for your crash with your crash report so that I can investigate further.

**Comment by Jeleven99** [comment]
I‘m sorry for answering this messages a little late. Here is the crash report:
[crash-2020-08-19_20.39.31-client.txt](https://github.com/MysticMods/Roots/files/5096568/crash-2020-08-19_20.39.31-client.txt). When I delated the  patchouli_data.json file、stated the game and opened the book ,the game still crashed.

**Comment by noobanidus** [comment]
@Jeleven99 This is an issue with Patchouli. Please try the latest version (1.0-21) and if that does not fix it, file an issue on their tracker. There is literally nothing I can do to fix it.

**Comment by noobanidus** [comment]
@Jeleven99 Again, please do not use old issues. Open a new one for your problem.
