### ISSUE TITLE
Runestone Brick Alt looks exactly like Runestone Brick when placed in world.

### ISSUE THREAD

**Issue by SiliconEnt** [MysticMods/Roots#174]
The title pretty much says it. Once roots:runestone_brick_alt is placed in the world, it loses the texture it has in the player's inventory, and shares the texture of roots:runestone_brick. This doesn't affect any of runestone_brick_alt's derivatives – slab, stair, wall, button, and plate retain their inventory textures when placed. 

I've already fixed the issue for myself in 3 minutes with a resource pack, but I figured I may as well submit the issue for the record. The root (pun intended) of the issue is that the runestone_brick_alt blockstate file points to the runestone_brick model, and the runestone_brick_alt model simply doesn't exist.

**Comment by duely** [comment]
Whoops. I made a typo in the blockstate file!
