### ISSUE TITLE
JEI not respecting meta data for bark recipes

### ISSUE THREAD

**Issue by Kiyaku** [MysticMods/Roots#178]
Adding custom bark recipes using blocks with different meta data works fine, however they don't show up properly in JEI. 

Example script:
```
Bark.addRecipe("weedwood_bark_1", <thebetweenlands:log_weedwood:0>, <roots:bark_oak>);
Bark.addRecipe("weedwood_bark_2", <thebetweenlands:log_weedwood:12>, <roots:bark_oak>);
```

This should add versions of the weedwood logs (one that looks like a normal log, one that is covered in all bark). 

However, JEI shows both recipes with meta 0 only:
![JEI](https://i.imgur.com/IDA8DEB.png )

**Comment by duely** [comment]
Okay, I think I can safely say that this got fixed (although I forgot to mention this bug in my commit message): 

![](https://i.imgur.com/nQJMo8y.png)
