### ISSUE TITLE
Animal Harvest Ritual Whitelist

### ISSUE THREAD

**Issue by squirrelkiller** [MysticMods/Roots#179]
Animal Harvest is a neat and unique ritual, however currently it doesn't allow you to add mobs from other mods into a whitelist to get their drops. A request for this to be added as a config.

**Comment by duely** [comment]
Given the various number of configurable aspects, we've actually avoiding using configuration files for things as they are generally pretty limited. Instead, [you can accomplish this specifically through the Animal Harvest ritual functionality in CraftTweaker, documented here](https://docs.blamejared.com/en/#Mods/Roots_3/animalharvest/).

**Comment by duely** [comment]
(There is no plan to make this accessible without CraftTweaker as specifically as a configuration file.)

**Comment by squirrelkiller** [comment]
Ah, that is a bit obscure and hidden for just a while list, might need to document that somewhere more noticeable.

**Comment by duely** [comment]
Where do you think would be a good place to document it? I'm not sure if I can edit the Roots page on CurseForge at the minute but I had intended to link to the CraftTweaker documentation directly from there and potentially summarise what could be done with it.

**Comment by squirrelkiller** [comment]
Curseforge seems to be the right place, heck even just a url in one of the configs would be great compared to, well I didn't even realize you had Craft Tweaker support yet. A mod just finding its feet like this one rarely does.
