### ISSUE TITLE
Bewitchment Conflict with Living Arrows

### ISSUE THREAD

**Issue by squirrelkiller** [MysticMods/Roots#180]
I created Living Arrows, and attempted to use them with my Wildwood Bow. The Arrows were consumed, but nothing got shot. Both within and without the Wildwood Quiver.

**Comment by duely** [comment]
I just tested this with the release currently on the ArcArc server (as that's what I had open at the time) and I was able to:

- Fire the bow and shoot an arrow at the ground with just the bow & the arrows in my inventory, and then retrieve it
- As above but also with a quiver
- As above (without walking over them to retrieve it) with the arrows in the quiver (and then retrieve them by sneaking)

Can you give some more information about your testing environment? Specifically, Forge version and a list of other mods also installed.

**Comment by squirrelkiller** [comment]
New detail determined. Bow seems to function. Arrows are not firing. Full observered behaviour is as follows:

When using a bow with Living Arrows in primary play environment (contents below), drawing the bow functions as it should.
Releasing the use button does not fire an arrow.
Arrow stack appears to decrease by 1 as if arrow was used.
Bow durability reduced accordingly.
Attempting to move the arrow stack in inventory shows the stack has, in fact, not changed, it only appears to change, and is in fact unchanged and updates to such when the item stack is updated.
Bow durability is truly reduced.
Tested against all other modded arrows in pack as well as alternative bows. Behaviour consistent.

Attempted to summon arrow entity from roots. Does not exist on its own.

Created Roots and dependencies only instance for testing. Fully functional moving the issue to being a conflict related to the arrows.

Moving test on to suspected mods.

Have a directory dump for the modslist. Forge version 14.23.5.2838. Single player.
[modlist.txt](https://github.com/MysticMods/Roots/files/3533601/modlist.txt)

**Comment by squirrelkiller** [comment]
Conflict found, it is bewitchment.
Cross reported. One of you is doing something naughty to the arrow entity. I will leave it to those who know the code to point the fingers and determine the fix.

https://github.com/Um-Mitternacht/Bewitchment/issues/417

**Comment by duely** [comment]
I'm 99% sure that the issue is on their end as [EntityLivingArrow](https://github.com/MysticMods/Roots/blob/master/src/main/java/epicsquid/roots/entity/item/EntityLivingArrow.java) merely extends the base default arrow and otherwise functions identically to a normal arrow -- it simply overrides the arrow returned (so it doesn't swap living arrows for normal arrows).
