### ISSUE TITLE
Known issues (please check here before opening an issue)

### ISSUE THREAD

**Issue by noobanidus** [MysticMods/Roots#183]
Note: If your error relates to CraftTweaker, please remember to include your `CraftTweaker.log` file, even if it seems unrelated.

#125 Special compatibility is required for the Harvest spell to work with Rustic crops, especially those on crop stakes or vines. ***Edit***: Simple Corn and Tea, the Story have also been added to this list. ***Workaround***: You will need to harvest these by hand, as otherwise the plants' growth is reset to 0 and no drops are given.

#208 Carrying multiple pouches introduces confusion to the spell system, as it generally checks the first pouch it encounters (generally in the Baubles slot, if installed) for herbs and then ignores any future pouches. If your herbs are split amongst multiple pouches, it may be confusing for you. ***Workaround***: Make sure the pouch you want herbs to be drawn from is on your hotbar or otherwise before other pouches.

#211 Pyre HUD may sometimes not display properly. ***Workaround***: The cause of the issue is still uncertain, so there is no workaround at this time.

#328 The mod [Transmutation Alchemy](https://www.curseforge.com/minecraft/mc-mods/transmutation-alchemy) causes a conflict with Runic Shears, preventing them from being used. ***Workaround***: Uninstall Transmutation Alchemy.

#355 Roots particles (and other additive particles) lose all colour with some version of Electroblob's Wizardry. If you are experiencing this and looking for a cause, this may be the issue. (This was a stale issue and the root cause may have been fixed in the meantime).

No issue: [a special compatibility mod is required in order to support Dynamic Trees](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-roots). This affects saplings grown and causes the Wildroot Growth ritual to spawn some seeds. 

No issue: (related to the above): the Spreading Forest ritual doesn't support Dynamic Trees and most likely will not support Dynamic Trees.

**Comment by Davoleo** [comment]
gonna close this isssue since it's quite outdated and most of its linked threads have been already fixed and closed
