### ISSUE TITLE
Patchoil book problems

### ISSUE THREAD

**Issue by guide-for-you** [MysticMods/Roots#184]
Mystical World don't have some mentions on how to tame mob:
![2019-08-24_19 00 09](https://user-images.githubusercontent.com/53404970/63639945-de69fb80-c6a2-11e9-8766-0e69936b40f3.png)
Roots:
The new ritual don't have discription in book(I'm talking about Gathering):
![2019-08-24_19 12 11](https://user-images.githubusercontent.com/53404970/63639966-3acd1b00-c6a3-11e9-9068-d9848b5d7d50.png)

![2019-08-24_19 00 38](https://user-images.githubusercontent.com/53404970/63639960-2f79ef80-c6a3-11e9-89ab-a393da5d9a70.png)

![2019-08-24_19 00 45](https://user-images.githubusercontent.com/53404970/63639974-491b3700-c6a3-11e9-8692-1719e770c170.png)

![2019-08-24_19 00 48](https://user-images.githubusercontent.com/53404970/63639975-4c162780-c6a3-11e9-8240-907faa3ecfcb.png)

**Comment by duely** [comment]
Thanks for the issue! I knew about this, I just haven't had time to rectify hte problem, but having an issue filed for it means I won't forget (which is what I did do when I released without it)!, so thank you so much.
