### ISSUE TITLE
Suggestion:Ideas for Roots 3

### ISSUE THREAD

**Issue by Wotzinator** [MysticMods/Roots#2]
if im honest i never really played much of roots because of how tiny it looked and many other good magic mods where released and as i got time for trying it out roots 2 was out and many of the features that seemed interesting where gone  and since the project changed the developers i thought i could make some suggestions for the mod i hope they are good even though i don't know the mod very good.

3.Support other magic mods like thaumcraft 6 ,botania and things like that .one thing you could do would be to add more bark for other magical trees or adding thaumcraft aspects to your items.

4.maybe adding more 3d models to items and a few multi blocks.

5.more weaponry like a bow or arrows with effects staff effects on them.

**Comment by EpicSquid** [comment]
Point 1 and 2 are now done, the rest are being considered as we get closer to release

**Comment by Wotzinator** [comment]
ok ill take them from the list.or are the other ideas(3-5)bad?

**Comment by Wotzinator** [comment]
btw what about the shield from point 2?

**Comment by EpicSquid** [comment]
Shield is a todo, supporting more magic mods is definitely planned (though not for a bit still). More weapons are planned, and 3D models will really just depend on what it makes sense to have models for.

Do you mind splitting these 3 ideas into separate issues? Makes it clearer what needs working on
