### ISSUE TITLE
Magmatic soil XP is given even on ungrown crops

### ISSUE THREAD

**Issue by SkyLord-Volmir** [MysticMods/Roots#202]
Netherwart can be planted on Caelic, Aqueous, Magmatic, and Terran soils.  It will grow, but it will not have any special effects, so far as I can tell.  The easiest to see is Aqueous, which does not auto harvest.
I expect that either netherwart would not be plantable, or that it would have the usual effects of the soil.

Additionally, sugarcane can be planted on Aqueous soil but does not seem to grow at all.

**Comment by duely** [comment]
Hm, that's annoying. Netherwart is meant to be plantable on any elemental soil, however. Did you have a chest or container under the aqueous soil? I'll investigate that further.

Sugar can is intentionally plantable on aqueous soil, I'll have to triple check as to why it's not growing though.

**Comment by SkyLord-Volmir** [comment]
Appologies for not including a version: This was on Roots 3.0.7.  The server I play on has just updated to Roots 3.0.10, which fixes at least the Aqueous Soil bug, as what was once fully grown nether wart just sitting there (unlike the auto-dropping wheat right next to it) is now never fully grown and my nether wart collection is growing.

Caelic seems to work faster now.
Magmatic has not grown and Terran gave me 1 or 3, so I can't tell yet if it's doing anything.
Still investigating whether sugarcane works as expected on Aqueous soil.

I will report back and possibly close the issue if I can't find anything weird.

**Comment by duely** [comment]
(Psst, it's Noobanidus, btw.)

Magmatic should give you XP when you harvest as well, randomly. Aqueous soil doesn't currently harvest cane because I couldn't make up my mind how to do it -- I think I'll have to special-case it.

**Comment by SkyLord-Volmir** [comment]
(Hi Noobanidus!)
I think aqueous soil actually is harvesting the sugarcane.  I have it set up next to a vacuumulator (Thermal Expansion) and while I never see it grow, I see the number in my storage very slowly growing.  No one is harvesting any by hand, and the only other auto input I have is a witch farm.

Breaking netherwart on top of magmatic soil does give experience....Even if it isn't fully grown!  You can just plant and break and get XP.  I'm not sure yet, but I think I don't get XP for harvesting full grown crops with right click from Quark. (We might be using a different right click mod on the server, but if so I can't find it)

**Comment by duely** [comment]
(The server is using EnderCore, which should be compatible). Re: breaking, that is ... not intended. I think HarvestDrops gets the original block state before broken, and that should be checking for max age value -- which I don't think it does. A bug!
