### ISSUE TITLE
Add Support to underground biomes mossy cobblestones

### ISSUE THREAD

**Issue by Mrthomas20121** [MysticMods/Roots#203]
would like to know if it would be possible to support underground biomes mossy cobblestones for roots? it's not a problem rn because underground biomes add a recipes to turn them into vanilla mossy cobblestone but would be nice if you could support them. ofc, they would have to turn into the cobblestone(not vanilla one, ex: shearing/knife on dacite mossy cobblestone should give dacite cobblestone)

**Comment by duely** [comment]
I intend to do this. Whether it is a configuration setting (with two pairs of itemstacks in the "mod:item:meta,mod:item:meta" format which denote two itemblocks), or whether it's a CraftTweaker function (likewise using ItemStacks or alternately using Block States which would allow the code to be considerably cleaner), I'm not sure. 

My main intent is to extend it away from just mossy cobblestone and also to mossy bricks.

Although I'm not sure if I would extend the overgrowth ritual to bricks, it is a possibility; it would also require a custom registry for block -> terra spores -> new mossy block, as well as an additional registry of mossy block -> terra moss -> non-mossy variant to replace with.

**Comment by duely** [comment]
So, ![](https://i.imgur.com/8tR5hUR.png)

This is what it looks like in game with the default configuration of:

```
    # List of mod:item:meta,mod:item:meta (meta optional) of mossy blocks and what to convert them into when scraping with knives
    S:MossyCobblestones <
        minecraft:mossy_cobblestone,minecraft:cobblestone
        minecraft:stonebrick:1,minecraft:stonebrick
        minecraft:monster_egg:3,minecraft:monster_egg:2
     >
```

I was going to make it primarily a CraftTweaker-based thing but I think it makes more sense as a configuration as it's such a core part of the mod. 

Should be in the next release!
