### ISSUE TITLE
radiance can be cast faster than mobs can take damage, causing spell components to be wasted

### ISSUE THREAD

**Issue by majijn** [MysticMods/Roots#210]

**Comment by majijn** [comment]
playing with radiance again, the fix doesnt really affect it, given how it seems to be channeled and doesnt use the cooldown until you stop casting the spell. so its still wasting spell components :(

**Comment by duely** [comment]
I didn't realise that it was wasting it during the channel period...

**Comment by majijn** [comment]
i hadnt realised it did that either! my bad tbh

**Comment by duely** [comment]
At this point in time, I'm not sure I can really do anything about how often the damage ticks versus how often the costs are exacted. I'll need to delve and find the average hurtTime value for creatures and adjust the cost tick accordingly.

**Comment by noobanidus** [comment]
The tick time still has to be adjusted.
