### ISSUE TITLE
Pyre identify tool tip goes missing on pyre ready to burn or ready to re-stock

### ISSUE THREAD

**Issue by VallenFrostweaver** [MysticMods/Roots#211]
Minecraft: 1.12.2
Roots: 3.0.12
Forge: 14.23.5.2838
See image for examples. Unable to consistently reproduce. Sometimes they work, others they don't.
![pyre ui](https://user-images.githubusercontent.com/13642054/64261171-ff90de80-cf23-11e9-9d0f-d5a7f01a9da1.png)

**Comment by duely** [comment]
Considering the position of your cursor, this isn't an issue of the tile entity not considered the target for rendering. I'll potentially add some debug statements to see if I can get to the bottom of it if I otherwise can't reproduce it.

**Comment by duely** [comment]
I'm going to assume this is because lastRitualUsed/lastRecipeUsed aren't being serialized to the tile, potentially the same thing causing #173 but I'll have to dig more -- it won't be in this release.

**Comment by noobanidus** [comment]
I'm going to presume that, as this hasn't been reported again, it's been fixed at some point between now and last September. If it hasn't, we can open a new issues.
