### ISSUE TITLE
Spreading Forest ritual doesn't recognize non-vanilla saplings

### ISSUE THREAD

**Issue by VallenFrostweaver** [MysticMods/Roots#212]
Minecraft: 1.12.2
Roots: 3.0.12
Forge: 14.23.5.2838
I used Quark Blossoming & Swamp oak saplings and it would only plant more vanilla oak.

**Comment by duely** [comment]
So, my assumption that most mods would extend BlockSapling turns out to be incorrect.

I either have the option of searching for IGrowables, or searching for blocks which contain "sapling" in the translation key, or... both. I'll look into it.

**Comment by duely** [comment]
As wire pointed out, the simplest solution here is to simply check the ore dictionary entries of the itemstacks dropped by leaves for treeSapling.
