### ISSUE TITLE
[Suggestion] Purify ritual needs a buff - cure villagers and "on fire"

### ISSUE THREAD

**Issue by VallenFrostweaver** [MysticMods/Roots#214]
Minecraft: 1.12.2
Roots: 3.0.12
Forge: 14.23.5.2838
In it's current state it does not remove burning. My suggestion is to remove this status effect as well as turn zombie villagers back into villagers.

**Comment by duely** [comment]
Fire extinguishing can definitely happen, I'm not 100% sure about villagers. I feel like they would need to be exposed to a certain *duration* of the purification ritual -- not necessarily as long as it takes to do the actual procedure, but certainly not just instantly.

**Comment by duely** [comment]
So, for villager zombies that are already converting, they'll do so twice as fast (Though not as fast if they're in an iron bar pen with a bed) in proximity to purify; also, it now extinguishes fire.

**Comment by VallenFrostweaver** [comment]
@duely This change to the zombie villager mechanic counteracts itself. The ritual removes the weakness potion condition before you can convert the villager. Therefore the change doesn't really change anything unless you start converting the zombie villager _outside_ the area and then push them into the area while they are converting. This being a damaging mob makes it especially difficult.

**Comment by duely** [comment]
That is an excellent point that I hadn't considered. I think I might buff it and only remove negative effects from non-hostile creatures.
