### ISSUE TITLE
[Suggestion] Spreading Forest pyre ritual needs a growth buff

### ISSUE THREAD

**Issue by VallenFrostweaver** [MysticMods/Roots#215]
Minecraft: 1.12.2
Roots: 3.0.12
Forge: 14.23.5.2838
Casting the ritual multiple times generated a lot of saplings but not many trees. The tree fertilization needs a buff.  I spent 10 rituals before it finally filled the area with trees and that's also only after I sped up the tick rate to 200. Likely would have taken longer if left to the regular tick rate.. It doesn't seem worth the investment currently.

**Comment by duely** [comment]
That is strange. You don't have anything else in your environment that reduces growth ticks, do you? Because the previous variant of the ritual ended up being so powerful that I reduced the rate slightly to compensate -- this being just Vanilla + Roots + requirements.

**Comment by duely** [comment]
Buffed! Hopefully enough.
