### ISSUE TITLE
Amethyst Advancement Error which blocks further advancements in Roots

### ISSUE THREAD

**Issue by Aracos80** [MysticMods/Roots#216]
Hi, first let me say i love roots, just pure fun to play :)

i've run into an advancement error while playing a custom modpack. 
im getting an error message that says i can continue playing.

https://paste.dimdev.org/ekuviwiqig.mccrash  <- this is the crash log

the first time i got this message, was when picking up amethyst, dont know if this is related.
but the message keeps popping up when i pick up wildroot or craft the book etc.

strange thing is that i dont get the achievement for those feats then and i think this blocks progression/unlocking chapters in the book.

i dont know if im at the correct spot for the error here or if this is related to mystical world but i hope someone can help

if you need additional info, please tell me and i will provide it

**Comment by duely** [comment]
I'm sorry, I have no idea what's causing this.

The line in question is `this.player.connection.sendPacket(new SPacketSelectAdvancementsTab(this.lastSelectedTab == null ? null : this.lastSelectedTab.getId()));`, and for a null pointer to exist here would seem to indicate that either `this.player` or `player.connection` is null. I'm not sure under which circumstances this would happen -- there's a specific check in making sure `this.lastSelectedTab` is not null. 

Have you been able to get any other advancements from Roots? Have you been able to get any advancements from any other mods? Are you able to see advancements when looking at the advancements tab? 

I suppose the final question is: are you playing on a modified client? If so, it's possible that advancements may not function correctly.

**Comment by Aracos80** [comment]
sorry for the delay of the answer (and sorry for my bad english, its a foreign language to me)

thanks to your suggestions i tried getting other achievements from roots and other mods (btw. it seems that every achievement was blocked).
i even created a new world an was baffled when every achievement worked

so i recreated every block/entity i used in my "crash" world and tried getting achievements and heureka! i found the sto

i tried automated creation of livingwood/stone from botania with the constructor/destructor blocks from **refined storage** and as soon as i added the destructor to my world (or as soon as i got the achievement for this) my whole achiement section went nuts and the error popped up again...

so i got into my "crash" world, deleted/destroyed the destructor blocks and every achievement worked again

so thanks for your tips which pointed me in the right direction and sorry for bothering you with an error created by a mod which you dont maintain

**Comment by duely** [comment]
No, it's fine, I'm just glad I could be of some help! That's a really strange bug. I would definitely make sure to post it on the Refined Storage page along with a link back to this issue. I'm glad that you've managed to continue progressing, as the Patchouli guide-book is based off advancements and it would be rather annoying not getting any...
