### ISSUE TITLE
Grove Stone disappering when you use it with Carry On mod.

### ISSUE THREAD

**Issue by guide-for-you** [MysticMods/Roots#220]

**Comment by Davoleo** [comment]
In my opinion, this should be reported to Carry On so the dev can add it to the default block blacklist

**Comment by guide-for-you** [comment]
Ok,thank

**Comment by guide-for-you** [comment]
Ok,thank

**Comment by duely** [comment]
Yeah, just break it and re-cast Grove Supplication.
