### ISSUE TITLE
baffle caps use stone sounds when placed or broken

### ISSUE THREAD

**Issue by majijn** [MysticMods/Roots#221]

**Comment by Davoleo** [comment]
Are you sure? 
the sound type in the code is set to Wood
https://github.com/MysticMods/Roots/blob/master/src/main/java/epicsquid/roots/init/ModBlocks.java#L63-L64

And also in my test world it seems to play the right sound
https://streamable.com/38dzl

**Comment by duely** [comment]
It's the actual BlockMushroomBase doesn't set the SoundType?

**Comment by duely** [comment]
I think it's an issue in Lib, I've fixed it there.

**Comment by Davoleo** [comment]
ok, nice!
