### ISSUE TITLE
Quiver incompatibility with Simply Arrows

### ISSUE THREAD

**Issue by Cre8or** [MysticMods/Roots#235]
[(taken from this Discord discussion)](https://discordapp.com/channels/455383608773836801/596485879028252673/620199153938726923)

Using arrows from the [Simply Arrows](https://www.curseforge.com/minecraft/mc-mods/simply-arrows) mod inside the quiver, then firing at the ground and picking the arrow(s) back up (using the custom "shift"/sneak feature) will yield vanilla arrows instead, effectively converting the arrows.

**Comment by noobanidus** [comment]
I'm so dumb.
