### ISSUE TITLE
Crash on startup with Unlimited Chisel Works

### ISSUE THREAD

**Issue by katubug** [MysticMods/Roots#239]
Hello! I am working on a modpack update and Roots is included in the new version. I deleted all the config files for all my mods to allow them to regenerate, and when starting the game up in order to do this, received this crash: https://paste.dimdev.org/exeqijoyuz.mccrash

The UCW config did not populate (file was created, but empty), so I'm guessing the error occurred around that time.

I then temporarily disabled Roots, and loaded up the game to get the UCW config populated so I could exempt Mossy Cobblestone from its list. However, apparently, vanilla blocks cannot be blacklisted via the config. I then tried restarting the game with the config generated, just in case it worked. It did not.

Minecraft version: 1.12.2
Forge version: forge-1.12.2-14.23.5.2838-universal
Roots: Roots-1.12.2-3.0.13
UCW: UnlimitedChiselWorks-0.2.4

Thanks for your time!

**Comment by katubug** [comment]
I- uh, oh. Perhaps I was wrong about UCW, as I disabled it and get the same crash: https://paste.dimdev.org/lapitopeni.mccrash

This time, the "suspected mods" include Deep Mob Learning.

**Comment by wamc2017** [comment]
Did you try updating MysticalLib to 1.3.7? (https://www.curseforge.com/minecraft/mc-mods/mysticallib/files/2780930)

**Comment by katubug** [comment]
Boy is there egg on my face. Yep, that fixed it entirely. I'm very sorry for the trouble, thank you for the help!

**Comment by duely** [comment]
So, I've been putting in specific required versions for mods but it looks like this is occurring before Forge gets to that point.
