### ISSUE TITLE
Crash with patchouli on start

### ISSUE THREAD

**Issue by uiytt** [MysticMods/Roots#264]
Ok so my small modpack works fine without roots (patchouli is used for another mod), but when I add roots, my game crash when I launch it.
Here the logs : https://pastebin.com/N3W889LM

Do you have any idea where its from ?

**Comment by Davoleo** [comment]
sounds like a version mismatch 🤔

**Comment by uiytt** [comment]
Wow it was fast xD

Well I have the latest version of patchouli, forge and roots.. And i'm in 1.12.2 so I don't know

**Comment by wamc2017** [comment]
The latest version of Mystical Lib is [1.3.7](https://www.curseforge.com/minecraft/mc-mods/mysticallib/files/2780930), according to the log you've 1.3.6 installed...

**Comment by duely** [comment]
Yeah, you need to update Roots, Mystical World and Mystical Lib.
