### ISSUE TITLE
Right-click active bonfire with knife to see range of ritual

### ISSUE THREAD

**Issue by noobanidus** [MysticMods/Roots#287]
"Spectral Hoe" is kind of what I'm leaning towards at the minute but I'd accept suggestions.

**Comment by majijn** [comment]
what about spectral kindling? 
divinatory kindling? 
kindling of augury?

sticks and a moss to craft (smoke lets you see the range)

**Comment by duely** [comment]
Sickle of Seeing? It fits in with the nature aspect, it's... kinda fits in with some types of neo-Druidism, and it's from the Key of Solomon!

**Comment by Trivicus** [comment]
Dowsing wand?

**Comment by duely** [comment]
Ooh, dowsing rod would work even more perfect!

**Comment by noobanidus** [comment]
I'm now indecisive about how to implement this.
