### ISSUE TITLE
clarify that elemental soil must touch top face of lava to transform

### ISSUE THREAD

**Issue by majijn** [MysticMods/Roots#298]
i tried throwing it on the side of a lava sourceblock because it was already placed and at hand , and it doesnt transform and burns.

**Comment by duely** [comment]
That's... interesting and also a bug.

**Comment by majijn** [comment]
if you have a hopper under the lava it still doesnt transform but it doesnt burn

**Comment by duely** [comment]
That's just the nature of the hopper, I think. It picks up the event before the EntityItem actually detects that it's in lave and can transform.
