### ISSUE TITLE
wildwood tree doesnt use the sapling growth event

### ISSUE THREAD

**Issue by majijn** [MysticMods/Roots#299]
i think? because if it is i dont kmow why it isnt being caught, tried using both the ritual and the sapling block and neither had the effect i was expecting.

**Comment by duely** [comment]
Uh, I think it just directly uses growTree. I should check to see if it should fire the sapling growth -- for the ritual I will ignore the result because I don't want anyone to cancel it, but cancelling the sapling should be fine...

**Comment by duely** [comment]
![](https://i.imgur.com/2ErZ2ll.png)

![](https://i.imgur.com/XPPLVVA.png)

Growing the sapling with bone meal directly results in this. I'm happy with it not working with the ritual, but it should actually work.
