### ISSUE TITLE
Fairies spatial awareness

### ISSUE THREAD

**Issue by Vordyn** [MysticMods/Roots#3]
Suggestion:

Would it be possible to give Fairies a small sense of their surrounding and allow them to detect that what they're about to fly into is a fluid and to avoid flying into it?

  We've been playing Exoria for the last while and while seeing the fairies flying around is cute, hearing them fly into lava continuously and hearing their death throes is REALLY getting annoying.

  Since the spawn list on the Exoria dimension is solely made of Fairies, the number of them is staggering so there will always be a dozen of them stuck in various lava or acid pits.

Thank-you.

**Comment by EpicSquid** [comment]
Thats a fair enough request, I'll look into it.

**Comment by EpicSquid** [comment]
Update: Roots 3 fairies are not implemented yet, but I am pretty sure I know what this issue is
