### ISSUE TITLE
Spell ingredients disappear randomly in the pouches

### ISSUE THREAD

**Issue by slayer6409** [MysticMods/Roots#307]
If I have less than a full stack of an item like Terra Moss or Spirit Herbs in any of the pouches and I try to full the stack, when I exit the GUI they revert back to the amount  that was in it before I tried to fill the stack. 

A current workaround I found is taking all of the stack out, closing the GUI, and then putting them back in.

Using: 
Roots-1.12.2-3.0.13
Forge-14.23.5.2846
in the Glacial Awakening Modpack

YouTube video of bug also with workaround:
https://www.youtube.com/watch?v=G0Wd4G-p_0o

**Comment by duely** [comment]
I *have* fixed this bug ... I *think* ... in the next released version, which will be 3.0.14. I'll need to triple check if it has been or not. The release has been a bit delayed for various reasons.

**Comment by duely** [comment]
I'd be curious if this is still happening with 3.0.15?

**Comment by duely** [comment]
Disregard, can confirm this is still happening with 3.0.15. Whyyy.

**Comment by noobanidus** [comment]
I don't remember if I fixed this. But I plan to rewrite pouches and quivers.

**Comment by noobanidus** [comment]
Needs confirmation if this is still happening. I might delay the release of 3.0.22 to reimplement as NBT-backed capabilities.

**Comment by noobanidus** [comment]
Okay, unable to replicate this, so I'm going to hold off on re-implementing pouches and quiver.
