### ISSUE TITLE
Pouches inventory misalignment 

### ISSUE THREAD

**Issue by luxlacis** [MysticMods/Roots#308]
When opening a pouch inventory, the whole gui is shifted slightly as shown in the image. Not sure what's causing this. Using the latest forge and mod version.

![2019-09-28_12 11 45](https://user-images.githubusercontent.com/47873040/65815647-40f67000-e1ea-11e9-94f4-3ee2c5fc37ef.png)

**Comment by duely** [comment]
Thanks for your report! Can I ask what your resolution is, and what your GUI Scale value is so I can try to reproduce it? As far as I can see, that is actually perfectly aligned, but for some reason (you can tell by the edge of the player inventory aligning with the edge of the hotbar, and likewise by the JEI search box covering the last item on the hotbar) JEI is bigger than it should be...

**Comment by luxlacis** [comment]
Sorry, should have said it earlier, I'm using Large GUI (even though it's the same with any gui size) at 1920x1080 fullscreen (but it's the same with windowed too). The image shows what mods I'm using.
![explorer_3u9WSc4cYw](https://user-images.githubusercontent.com/47873040/65828141-87ea7100-e28f-11e9-8732-148769ac1c2f.png)

**Comment by duely** [comment]
I'm more inclined to believe it's either a JEI bug, or the screen itself is larger than it's *telling* Minecraft what it is, hence JEI thinks it gets more space... I'll add this to the to-do for 3.0.14

**Comment by duely** [comment]
Actually, the placement of Quark's trash bin definitely indicates that something's off...

**Comment by luxlacis** [comment]
Thank you. In the mods list screenshot i removed quark and many other mods to show that it's not their fault. And the other couple mods I left really shouldn't be affecting this mod, so I left them. Good luck with fixing the issue! 😄
