### ISSUE TITLE
Transmutational Alchemy conflicts with Roots 3 and prevents Runic Shears from functioning

### ISSUE THREAD

**Issue by DoCharlcate** [MysticMods/Roots#328]

**Comment by Davoleo** [comment]
is this this related to #326 ?

**Comment by DoCharlcate** [comment]
It very well could be. I know it was all working fine a couple of days ago but since then I have not been able to shear fey leather whatsoever. The runic shears do still work for shearing multiple sheep though but nothing at all happens when you try to shear fey leather.

**Comment by duely** [comment]
I think that's slightly unrelated. I'm going to put out another hotfix.

**Comment by duely** [comment]
#330 is also most likely related. I need to think about how to handle this.

**Comment by duely** [comment]
Please let me know if 3.0.16 which was recently released onto CurseForge (and hopefully already approved) fixes this for you. I changed how the Runic Shears worked but failed to change the name, so older saves were attempting to load incorrect information into the new methods... whoops!

**Comment by DoCharlcate** [comment]
Unfortunately not. Tried it in a new world on both cows and deer and it's still doing nothing.

**Comment by duely** [comment]
Can you upload your `latest.log` file to Gist for me from a session where you've been unable to shear?

**Comment by DoCharlcate** [comment]
[latest.log](https://github.com/MysticMods/Roots/files/3706551/latest.log)

**Comment by DoCharlcate** [comment]
Dang. Actually I just started a new pack with just roots and mystic world and that seems to work fine. So must be a recent thing with another mod update that has changed the models like Charm or Quark. Sorry I should of tested that first before coming here. I just thought as things were working fine with other mods up until a couple of days ago, something must of changed with roots. 

I'll keep testing what mod might be conflicting with it. Should I post it here when I find the culprit or on that mod authors github?

**Comment by duely** [comment]
That's fine -- I would appreciate it! It might just be the fact that something got corrupted in the world with the latest update and my hot-fix (as it were) wasn't quick enough to catch it... if you do find a mod responsible, that would be good to know -- but I don't think there will be one.

**Comment by DoCharlcate** [comment]
I don't think it was a corrupted world as I created another world with the offending mod pack and things were still not working but I'm not sure how the whole corrupted world thing works or if it bleeds over to new worlds. 
Leave it with me. I'll see what mods were updated recently and individually load them into the new pack and see if I can recreate the issue.

**Comment by duely** [comment]
Thank you for that! I'm going to rename this issue and leave it open for future reference.

**Comment by duely** [comment]
(Most likely they just have an on-entity-interact that's firing and canceling the event before the shears can properly be used.)
