### ISSUE TITLE
Recipe search for Fey Leather causes crash when JER is not installed.

### ISSUE THREAD

**Issue by BookerCatch** [MysticMods/Roots#329]
Searching the recipe for Fey Leather without Just Enough Resources installed crashes the client.

**Comment by Davoleo** [comment]
yep, was able to reproduce this clicking on runic shearing tab
https://pastebin.com/VzSyCGgm

**Comment by duely** [comment]
That would be because I was cribbing JER code and assumed that RenderHelper was a Minecraft function, forgetting the fact that JER was actually included in our dev environment.

**Comment by duely** [comment]
Yup, so RenderHelper's entity functions aren't GuiScreenInventory.drawEntityOnScreen. I mean, they're basically the same code... anyway, I've fixed this in release 3.0.16. I do recommend Just Enough Resources though! It's a great mod and our elemental soil now has full compatibility!
