### ISSUE TITLE
is this is an issue with 3.0.15?

### ISSUE THREAD

**Issue by kreezxil** [MysticMods/Roots#330]
exceprt from console
https://gist.github.com/kreezxil/2be57dd23f3c788b2dc652b43a298295

roots is mentioned at the bottom, experience says your mod is not at fault here, I wonder if any mod is at fault. Gonna ask the Divergent Underground author next.

oh it says a cow can't be spawned.

**Comment by duely** [comment]
Hoo boy. I ... hadn't really considered how this might be an issue and am even now regretting my decision not to use a potion effect. I'll issue a hotfix.

**Comment by duely** [comment]
I'm hopeful that 3.0.16, just pushed and hopefully soon approved on CurseForge, will fix this issue completely.
