### ISSUE TITLE
Crash when placing Wildewheet in Animania Trough

### ISSUE THREAD

**Issue by katubug** [MysticMods/Roots#331]
It was reported in the Animania discord that a person had customized the Animania Troughs to accept Wildewheet - but upon placing it into the trough, crashed. I set up an instance with only Roots, Animania, and their dependencies, and was able to replicate it.

When the crash occurred, it had a long "pause" where the screen when bright before actually producing the crash, which put me strongly in mind of the behavior of this crash that I reported to the MysticalWorld github: https://github.com/MysticMods/MysticalWorld/issues/56

Their crash: https://paste.dimdev.org/kokiqetele.mccrash
My crash: https://paste.dimdev.org/adomibutuh.mccrash

* **Minecraft version:** 1.12.2
* **Forge version:** forge-1.12.2-14.23.5.2838-universal
* **Mod versions:** 
- animania-1.12.2-1.7.2
- CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha
- Roots-1.12.2-3.0.13
- MysticWorld-1.12.2-1.4.4
- mysticallib-1.12.2-1.3.7
- Patchouli-1.0-20
(and also JEI, ToP, and Journeymap, but I don't think those are related)

Thanks very much for your time!

**Comment by duely** [comment]
This is the same issue as with CCL/Direwolf's... yeah, there isn't an actual texture to get the colour from to work how they'd like to work. I need to convert the item models as well but ... yeah that slipped my mind. **That** was the one thing when I was talking to my dad about programming the day before the release, I was like "there's **one** thing I have to do but I can't remember it" and I didn't remember it until now :(

**Comment by katubug** [comment]
I absolutely know how that goes. Usually moments after I get my new modpack update installed on my server, lol. No worries about it! Thank you for the quick response, hope it's not too onerous to code.

**Comment by duely** [comment]
No, it's just a matter of changing a few variables in my generation script and then coding everything up... hopefully I'll have it out in the next Mystic World update, although that may be a little while... so potentially Roots will be done before then.

**Comment by duely** [comment]
This should be resolved in the next version for roots.
