### ISSUE TITLE
Pump water out of an unending bowl?

### ISSUE THREAD

**Issue by DoomRater** [MysticMods/Roots#332]
This is one of the smallest infinite water supplies out of every mod out there and automating it would be a lot of fun.

**Comment by duely** [comment]
That's interesting, I thought this was already a possibility...

**Comment by duely** [comment]
So, this is not currently a possibility and the entire Unending Bowl has to be completely rewritten, hooray! It shouldn't take too long and it will most likely end up being shorter.
