### ISSUE TITLE
Animania animals do not count as pacifist mobs

### ISSUE THREAD

**Issue by DoomRater** [MysticMods/Roots#333]
I'm going to add them by hand for now, but nearly every mob in Animania is a replacement or addition to a vanilla mob.  As such, their inclusion as pacifist eligible mobs seems appropriate.  In addition, since they can outright replace vanilla mobs via config, the essence harvest rituals should work on them too, otherwise there's no pacifist way to get animal drops.

**Comment by duely** [comment]
I realise this is a recent addition to the Roots project page on CurseForge, but the [Animal Harvest Ritual](https://docs.blamejared.com/1.12/en/#Mods/Roots_3/animalharvest/) and the list of [Pacifist Mobs](https://docs.blamejared.com/1.12/en/#Mods/Roots_3/pacifist/) are fully configurable through CraftTweaker, and this is the desired method of adding or removing from those tables.

I may at some point ship example Animal Harvest/Pacifist CraftTweaker scripts for a variety of mods (Animania included) so it's a simpler process of just drag-and-drop, however at this point in time I'm focused on new features.

**Comment by DoomRater** [comment]
No worries- setting up CraftTweaker to take care of the task has taken me about half an hour, after writing an autohotkey script to help automate the process of tacking on about... 150+ entities for Animania alone.  Better Animals Plus and Twilight Forest will probably go a lot faster.
