### ISSUE TITLE
Can't collect leather fey with runic shears

### ISSUE THREAD

**Issue by Ezylox** [MysticMods/Roots#347]
Hi !

Runic shears are working properly excepted for collecting leather fey. They are just not doing anything. 

I don't have any crash report but i have this bug sometimes who's making my game crash whenever i try to quit and save but i don't think it's related to Roots.

I can't post the log here, the website is freezing whenever i paste it and i don't have a pro account on pastebin. You will need to download it. 

http://www.mediafire.com/file/5nn1btyasjsbbh4/2019-10-15-2.log.gz/file

And here's my mod list

https://imgur.com/hPuF3B1

Have a good day !

**Comment by Seth0067** [comment]
+1 here.

Via most recent version of "Dimension Zero" pack via Twitch launcher in case it helps with debugging.
[Dimension Zero @ Twitch/Curseforge](https://www.curseforge.com/minecraft/modpacks/dimension-zero)

**Comment by duely** [comment]
Presuming you're using 3.0.17, if both of you could try out the following and then upload the log file, I've released a version with a number of debug statements to try tracking down what the issue could be: [Roots-1.12.2-3.0.17-rstest.jar.zip](https://github.com/MysticMods/Roots/files/3736786/Roots-1.12.2-3.0.17-rstest.jar.zip)

**Comment by duely** [comment]
Okay, I've installed the "Dimension Zero" pack, and the first issue I've noticed is that I should be checking for Runic Shears recipes before testing for IShearables, as shearing Cows seems to turn them into Demon Cows (or maybe I used the wrong spawn egg); on that same note, however, I got the following:

```[10:06:06] [Client thread/INFO]: [Runic Shears] Attempting to use Runic Shears on mysticalworld:entity_deer
[10:06:06] [Client thread/INFO]: [Runic Shears] No suitable recipe found for mysticalworld:entity_deer```

So I'm not entirely sure what's going on there. I'll need to dig into the code and perhaps add some more CraftTweaker commands to dump recipes to see where things are being removed from...

**Comment by Seth0067** [comment]
@duely i've called this to the attention of the packdev and linked him to this discussion.  i can not comment on above.

**Comment by Ezylox** [comment]
Hi, here's the log
[latest.log](https://github.com/MysticMods/Roots/files/3739783/latest.log)

**Comment by duely** [comment]
That's *really* disconcerting. I'm just working on a build that includes a way to dump Runic Shear entity recipes to see what's missing. I'l try to upload that shortly.

**Comment by Spiderfoxtail** [comment]
I ran into this same issue with my mod pack a few days ago. After testing the mods one by on with it, it turned out to be a conflict between Matchlock guns and Roots. When both in the same mod pack, you cannot get fey leather to drop with the runic shears. It doesn't look like the same error is happening here, but maybe it will shed _some_ light.

**Comment by duely** [comment]
I think I might potentially have a fix for the issue, if it is indeed the fact that the generated entity list is being generated *way* too early.

**Comment by duely** [comment]
I think I've resolved it, I'll try to get a new release of Lib/Word/Roots out presently.

**Comment by Ezylox** [comment]
It's working for me !
Thank you !

**Comment by duely** [comment]
I'm going to close this; if anyone is still having issues, please comment again and I'll reopen, but I believe this fix should cover the main problem.
