### ISSUE TITLE
Ritual of summoning not working

### ISSUE THREAD

**Issue by LennartCockx** [MysticMods/Roots#348]
Adding the required items will show the icon of the summoning ritual above the pyre, I then add raw beef or leather to a offering plate., but I cannot seem to light the pyre. Other rituals work fine, but this one does not activate.

**Comment by majijn** [comment]
youre probably missing standing stones @LennartCockx

**Comment by LennartCockx** [comment]
That's what I initially thought as well, but the in-game guide does not specify the need for standing stones for this ritual and any video I can find of this ritual seemingly does not require any.
I tried a couple of configurations similar to other rituals, but to no avail.

**Comment by noobanidus** [comment]
This is now invalid with the changes to the Ritual of Summoning. We can revisit if there are still issues, but the conditions now give a more valid feedback.
