### ISSUE TITLE
Baykok's Bow from Totemic and the Sentient Bow from Blood Magic consumes Wildwood Quiver

### ISSUE THREAD

**Issue by FlyGuy240** [MysticMods/Roots#349]
Whenever I use Baykoks bow, or the sentient bow it consumes the entire quiver (with the entire inventory) upon firing one shot. It will fire arrows in my inventory first, but seems to treat the quiver as an arrow itself

**Comment by duely** [comment]
Those are issues for the relevant mods. They aren't checking if the arrow itself is infinite ammo, but they're checking for an enchantment on the bow. This means they're still using 1.7.10 logic/code rather than the new 1.12.2 method.
