### ISSUE TITLE
aubergines from other mods not recognised as valid ritual recipe inputs

### ISSUE THREAD

**Issue by majijn** [MysticMods/Roots#351]
im guessing the recipes arent oredicted?

this also applies to recipes in mystical world.

**Comment by Davoleo** [comment]
I think aubergines are from mystical world, so it might be good to transfer the issue there @duely

**Comment by duely** [comment]
I think it's specifically referring to recipes for rituals, spells, etc, that include aubergines and don't specifically use the OreDictionary cropAubergine

**Comment by majijn** [comment]
yes as most recipes are in roots i decided to pit it here but its an issue in both, although having any cropeggplant/cropaubergine let you get seeds would (kind of) serve as a workaround

**Comment by Davoleo** [comment]
ah, ok
