### ISSUE TITLE
Pereskia recipe bugged in latest release

### ISSUE THREAD

**Issue by daforsyth** [MysticMods/Roots#352]
### General Information

**Describe the bug:**
In the latest update of Roots the pyre ritual to create Pereskia seems to be broken. The recipe doesn't exist and the in gamebook shows a recipe with 5 Pereskia bulbs making 5 roasted Pereskia 

**To Reproduce:**
Look inside book entry for Pereskia or use NEI to see recipe doesn't exist

### Environment Versions

Roots-1.12.2-3.0.19.jar

**Mystic Mods Versions**

- MysticalLib: mysticalworld-1.12.2-1.5.0.jar

**Other Versions:**
- Forge:  forge-14.23.5.2847
- Minecraft: 1.12.2
- Modpack (if available): Bewitchment Discord Server Pack (On Twitch)

![2019-11-01_21 47 39](https://user-images.githubusercontent.com/14133907/68065112-5b909d00-fcf2-11e9-8c63-21a4dfc4dcf9.png)

**Comment by duely** [comment]
This was fixed in 3.0.20
