### ISSUE TITLE
Actually Additions rice on terran soil drops cheese

### ISSUE THREAD

**Issue by NotGeorgeLucas** [MysticMods/Roots#354]
### General Information

**Describe the bug:**
Act. Additions rice from terran soil drops cheese, for some reason

**To Reproduce:**
1. Place terran soil, grow rice on it
2. Right-click harvest(with Quark)

**Expected behavior:**
As well as normal drops, you will get cheese
***

### Environment Versions
Roots 3.0.9; Actually Additions r149

**Mystic Mods Versions**

- MysticalLib: 1.3.4
- Mystic World: 1.4.3

**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge: 14.23.5.2847
- Minecraft: 1.12.2
- Modpack (if available):

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**
Pretty sure that's not needed in this case, right?

**Crash Report (if available):**

**Latest Log (if necessary):**

***

### Additional Information
**Screenshots (if available):**

**Additional context (optional):**

**Comment by duely** [comment]
That version of Roots is horrendously out of date. The most recent version is 3.0.20, which fixes this issue. Thanks for reporting it though! If you're playing in a pack, I'd recommend either manually updating Roots (if the pack isn't being updated), see if there is a pack update, or pester the pack author to update.

**Comment by NotGeorgeLucas** [comment]
Oh sorry for disturbing then

**Comment by duely** [comment]
No, it's fine, thank you so much for taking the time to report the issue!
