### ISSUE TITLE
Roots particles lose color when installed alongside Electroblobs Wizardry.

### ISSUE THREAD

**Issue by SirAron111** [MysticMods/Roots#355]
Currently EBWizardry has a strange rendering issue with overlays and certain particles causing it to make other mods lose colors and no one can find out why. Roots and Embers are some of the affected mods so I thought this I should link this issue here if anyone comes to report it or has found a reason why this happens so it gets directed to the conflicting mod. Or if anyone proficient comes along with what type of particles are used in these mods or in what instance they render and know what could be wrong etc

https://github.com/Electroblob77/Wizardry/issues/208
https://github.com/Electroblob77/Wizardry/issues/285

This is intended as an info on incompatibility I mean the mods still work fine they just lose the nice colors. Hope this helps anyone running into the same issue, so they don’t need to spend hours finding the cause.

**Comment by duely** [comment]
Yeah, ty, I'll leave this open as a known issue. It's definitely an issue with them failing to turn an OpenGL switch back on/back off.
