### ISSUE TITLE
Flower Growth Ritual causing crash on server only

### ISSUE THREAD

**Issue by kesryth** [MysticMods/Roots#356]
When lighting the pyre for the Flower growth ritual on a server, the pyre lights then the server crashes. Crash log indicates Ticking Entity - NoClassDefFoundError.
Attempted this on a single player world and crash does not occur. 

To Reproduce:
1. Prepare Flower Growth Ritual - Pyre w/ Dandelion, Poppy, Petals, Wildroot, & Terra Moss
2. Light pyre
3. Crash

**Expected behavior:**
Expect that, like in a single player world, the ritual would fire off and grow flowers without crashing.

### Environment Versions
Java 1.8.0_231-b11 (64-bit)
Mysticallib-1.12.2-1.4.0.jar
Mysticalworld-1.12.2-1.5.0.jar 
Forge-1.12.2-14.23.5.2847-universal.jar
Minecraft: 1.12.2
Patchouli-1.0-20.jar 
Roots-1.12.2-3.0.20.jar

### Logging Information

**Crash Report (if available):**
https://pastebin.com/KtMZvcPx

[crash-2019-11-05_22.15.14-server.txt](https://github.com/MysticMods/Roots/files/3812508/crash-2019-11-05_22.15.14-server.txt)

**Comment by duely** [comment]
That has me stumped. There's absolutely no reason why the update function should be trying to access client-side content...

**Comment by duely** [comment]
Do any of the other rituals crash in a similar way?

**Comment by duely** [comment]
Ah, disregard, I see the issue. I'll try to have a fix out soon.

**Comment by Davoleo** [comment]
I'm 100% sure it's one of my oversights

**Comment by kesryth** [comment]
Appreciate the quick review and response

**Comment by duely** [comment]
That's basically what I did, I just didn't get a chance to push & build as I was moving between places. I'll tweak a few things and try to get 3.0.21 out within the next 8 hours.

**Comment by kesryth** [comment]
I've got my test setup with both a clean world and my previously crashing world ready to test with. So I should be able to provide feedback fairly quickly

**Comment by duely** [comment]
All right, I think it's been more than 8 hours (sorry!) but the new Roots build addressing this is up. Please comment if you have any ongoing issues (hopefully there won't be any) and I'll re-open the issue.

**Comment by kesryth** [comment]
No problem at all. I know how busy life gets. 
No issues with the ritual when testing on a clean world (running only Roots and req dependencies), as well as my modpack world that had been in a crash loop from the ritual. Thanks for the quick turnaround!

**Comment by duely** [comment]
Awesome -- thank you! Honestly, it would've been faster, but I was considerably busier than I normally would've been and when I did have the time to actually do it, I'd just completely forgotten. :( Glad it's working!
