### ISSUE TITLE
pyre cooking crash

### ISSUE THREAD

**Issue by majijn** [MysticMods/Roots#357]
https://pastebin.com/3Na4QJpr

**Comment by Davoleo** [comment]
I can't seem to reproduce this, what's the recipe you've experienced a crash with?

**Comment by duely** [comment]
Were you trying to cook four potatoes?

**Comment by majijn** [comment]
i left it running with some water elemental soil growing potatoes. so yes at some points it would have tried to start with less than 5 taters

**Comment by duely** [comment]
Okay, that's probably going to cause it and that's interesting. I'll need to look into why it's doing htat.

**Comment by Mistmage** [comment]
I think there is an error in the same, but there is a problem in a custom recipe.
https://pastebin.com/N5MRHxxq

Also this error occurs if you put moonglow
automatically produced, but leave only one bark

I believe that any recipe using several identical ingredients will give this error if there is only part of it.

**Comment by noobanidus** [comment]
@Mistmage Can you give an example of your custom recipe for posterity? I'm pretty sure I know what the issue is, but additional information is helpful.

**Comment by Mistmage** [comment]
Yes of cource

 Pyre.addRecipe("2", <minecraft:gold_ingot>*2, [<poormetals:poor_gold_ore>, <naturesaura:gold_leaf>, <minecraft:coal_block>, <naturesaura:gold_leaf>, <poormetals:poor_gold_ore>]);

**Comment by noobanidus** [comment]
I'm pretty sure this is fixed, and it should be in 3.0.22.
