### ISSUE TITLE
Pyre Rituals JEI Integration

### ISSUE THREAD

**Issue by Davoleo** [MysticMods/Roots#95]
#### A separate JEI Recipe category for pyre rituals

- 5 slots for the ritual ingredients
- A button that opens the ritual-related patchouli book page
- _Some kind of visual effect that represent the ritual (optional)_

**Comment by Teibidh** [comment]
This looks to already be in place, partially? If I search JEI for an @roots item that requires a ritual and press R or click on it I get a "ritual" diagram that accurately depicts what needs to happen. There's no button to open the book, but the recipe is there.

**Comment by duely** [comment]
I think this is resolved now with the oncoming changes to crafting.

Opening hte Patchouli ritual page would've been good.

**Comment by Davoleo** [comment]
I'll re-open this since I'm working on a button that opens the respective patchouli page

**Comment by Davoleo** [comment]
on hold till this is implemented https://github.com/Vazkii/Patchouli/issues/94
